### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by prasethu** [scottksmith95/CSharp.Bitbucket#1]
@scottksmith95 Hey Scott, I see that this repo was last touched 3 years ago. 

Any idea if it still works?

I need the following:
1. Authentication with BitBucket
2. Clone a repo
3. Create a repo
4. Publish a local repo to BitBucket.

**Comment by scottksmith95** [comment]
Pretty sure it should. Coderbits still uses it for read purposes so I have not done a lot of testing with other functionality.

**Comment by prasethu** [comment]
@scottksmith95 Thanks!
